SELECT ID, IFNULL(PID.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA ED
LEFT JOIN (
    SELECT PARENT_ID, COUNT(PARENT_ID) AS CHILD_COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
) AS PID ON ED.ID = PID.PARENT_ID