-- 코드를 작성해주세요
SELECT D.DEPT_ID, D.DEPT_NAME_EN, ROUND(E.ESAL, 0) AS AVG_SAL
FROM HR_DEPARTMENT AS D
INNER JOIN (
    SELECT DEPT_ID, AVG(SAL) AS ESAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
    ) AS E
ON E.DEPT_ID = D.DEPT_ID
ORDER BY AVG_SAL DESC